(() => {
  const FILE_DB='studyflow-materials-v1';
  const MAX_FILE_SIZE=20*1024*1024;
  let fileDBPromise;
  const palette=['#39745e','#d89255','#6c83b5','#a078a5','#c36a5a','#5796a2'];
  const today=new Date(); today.setHours(0,0,0,0);
  const dayKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
  const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
  const fmt=(d,opt={weekday:'short',month:'short',day:'numeric'})=>new Intl.DateTimeFormat('en-IN',opt).format(d);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state={goal:12,subjects:[],tasks:[],exams:[]};
  let currentUser=null;
  let saveQueue=Promise.resolve();
  async function api(url,options={}){
    const headers=new Headers(options.headers||{});
    if(options.body)headers.set('Content-Type','application/json');
    const response=await fetch(url,{...options,headers,credentials:'same-origin'});
    if(response.status===204)return {};
    let payload={};try{payload=await response.json()}catch{}
    if(!response.ok){const error=new Error(payload.error||'The request could not be completed.');error.status=response.status;throw error}
    return payload;
  }
  function persistPlanner(){
    if(!currentUser)return Promise.resolve();
    const snapshot=JSON.stringify({planner:state});
    saveQueue=saveQueue.catch(()=>{}).then(()=>api('/api/planner',{method:'PUT',body:snapshot}));
    return saveQueue;
  }
  function save(){persistPlanner().catch(()=>toast('Could not save your planner. Check your connection and try again.'))}
  async function flushSave(){return persistPlanner()}
  function openFileDB(){if(!fileDBPromise)fileDBPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(FILE_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('files'))req.result.createObjectStore('files',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return fileDBPromise}
  async function getFiles(){const db=await openFileDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),req=tx.objectStore('files').getAll();req.onsuccess=()=>resolve(req.result.filter(file=>file.ownerId===currentUser?.id));req.onerror=()=>reject(req.error);tx.onerror=()=>reject(tx.error)})}
  async function putFile(fileRecord){const db=await openFileDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(fileRecord);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
  async function getFile(id){const db=await openFileDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),req=tx.objectStore('files').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function deleteFile(id){const db=await openFileDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
  const subject=id=>state.subjects.find(s=>s.id===id)||{name:'Independent study',color:'#8d948b'};
  const fmtHours=m=>{const h=Math.floor(m/60),r=m%60;return h?`${h}h${r?` ${r}m`:''}`:`${r}m`};
  const remaining=t=>Math.max(0,Math.ceil((new Date(t+'T00:00:00')-today)/86400000));
  function render(){
    const h=new Date().getHours();document.getElementById('greeting').textContent=h<12?'Good morning.':h<17?'Good afternoon.':'Good evening.';
    document.getElementById('today-pill').textContent=fmt(today,{weekday:'long',month:'long',day:'numeric'});
    const todays=state.tasks.filter(t=>t.date===dayKey(today)).sort((a,b)=>a.time.localeCompare(b.time));
    const weekStart=new Date(today);weekStart.setDate(today.getDate()-today.getDay());const weekEnd=addDays(weekStart,7);
    const weekTasks=state.tasks.filter(t=>new Date(t.date+'T00:00:00')>=weekStart&&new Date(t.date+'T00:00:00')<weekEnd);
    const doneMins=weekTasks.filter(t=>t.done).reduce((n,t)=>n+Number(t.duration),0),plannedMins=weekTasks.reduce((n,t)=>n+Number(t.duration),0);
    const completed=state.tasks.filter(t=>t.done).length,open=state.tasks.filter(t=>!t.done).length;
    const examNext=state.exams.map(e=>({...e,days:remaining(e.date)})).filter(e=>e.days>=0).sort((a,b)=>a.days-b.days)[0];
    const minsToday=todays.reduce((n,t)=>n+Number(t.duration),0);
    document.getElementById('metrics').innerHTML=[['Study time today',fmtHours(todays.filter(t=>t.done).reduce((n,t)=>n+Number(t.duration),0)),`${fmtHours(minsToday)} planned`, 'clock'],['Tasks completed',`${completed}`,`${open} still on your list`, 'check'],['This week',fmtHours(doneMins),`${fmtHours(plannedMins)} planned`, 'chart'],['Next exam',examNext?`${examNext.days} days`:'—',examNext?esc(examNext.subject):'Add an exam date', 'calendar']].map(([label,val,sub,icon])=>`<div class="metric"><div class="metric-top"><span>${label}</span><span class="metric-icon">${iconSvg(icon)}</span></div><strong>${val}</strong><small>${sub}</small></div>`).join('');
    document.getElementById('schedule-sub').textContent=todays.length?`${todays.length} session${todays.length===1?'':'s'} · ${fmtHours(minsToday)} planned`:'A clear day is a good place to start';
    document.getElementById('schedule').innerHTML=todays.length?`<div class="day-head"><div class="day-date"><div class="day-number">${today.getDate()}</div><div><div class="day-name">${fmt(today,{weekday:'long'})}</div><div class="day-month">${fmt(today,{month:'long',year:'numeric'})}</div></div></div><span class="focus-tag">${todays.filter(t=>t.done).length} of ${todays.length} done</span></div><div class="timeline">${todays.map(t=>{const s=subject(t.subject);return `<div class="time-label">${esc(t.time)}</div><div class="timeline-items"><div class="study-item ${t.done?'done':''}" style="--item-color:${s.color}"><div><div class="task-name">${esc(t.title)}</div><div class="task-meta"><i class="subject-dot"></i>${esc(s.name)} <span>·</span> ${t.priority===3?'High':t.priority===2?'Medium':'Low'} priority</div></div><div class="task-right"><span class="duration">${fmtHours(Number(t.duration))}</span><button class="check" data-toggle="${t.id}" aria-label="Mark ${t.done?'incomplete':'complete'}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><path d="m5 12 4 4L19 6"/></svg></button></div></div></div>`}).join('')}</div>`:`<div class="empty-state">No sessions planned yet. Add a task or let Studyflow build your week.</div>`;
    const insightText=minsToday===0?'Your calendar is open. Add a task or plan a week to create a steady rhythm.':`${fmtHours(minsToday)} of focused study is on your plan today. Start with one session and build momentum.`;
    document.getElementById('insight').innerHTML=`<span class="spark">${iconSvg('spark')}</span><div><b>A little nudge</b><p>${insightText}</p></div>`;
    const upcoming=state.tasks.filter(t=>!t.done&&t.date>=dayKey(today)).sort((a,b)=>a.date.localeCompare(b.date)||b.priority-a.priority||a.time.localeCompare(b.time)).slice(0,3);
    document.getElementById('up-next').innerHTML=upcoming.length?upcoming.map((t,i)=>`<div class="focus-row"><span class="focus-num">0${i+1}</span><div class="focus-info"><b>${esc(t.title)}</b><small>${esc(subject(t.subject).name)} · ${t.date===dayKey(today)?'Today':fmt(new Date(t.date+'T00:00:00'),{weekday:'short',month:'short',day:'numeric'})}</small></div><span class="focus-time">${fmtHours(Number(t.duration))}</span></div>`).join(''):`<div class="focus-row"><div class="focus-info"><b>You're all caught up</b><small>Add a task whenever you're ready</small></div></div>`;
    const exams=state.exams.slice().sort((a,b)=>a.date.localeCompare(b.date));
    document.getElementById('exams').innerHTML=exams.length?exams.map(e=>{const d=remaining(e.date);return `<div class="exam-row"><div><b>${esc(e.subject)}</b><small>${fmt(new Date(e.date+'T00:00:00'),{weekday:'short',month:'short',day:'numeric'})}</small></div><span class="days-away ${d<=3?'soon':''}">${d===0?'Today':`${d} days`}</span></div>`}).join(''):`<div class="empty-state">No exams added yet.</div>`;
    renderWeek(weekStart);renderSubjects();renderFiles();
    document.getElementById('week-hours').textContent=`${(doneMins/60).toFixed(1).replace('.0','')}h studied`;document.getElementById('week-goal').textContent=`of ${state.goal}h`;document.getElementById('week-progress').style.width=`${Math.min(100,doneMins/60/state.goal*100)}%`;document.getElementById('week-copy').textContent=doneMins>=state.goal*60?'Weekly goal reached. Nice work.':'Keep showing up for your sessions.';
  }
  function renderWeek(start){const wrap=document.getElementById('week-bars');wrap.innerHTML=Array.from({length:7},(_,i)=>{const d=addDays(start,i),key=dayKey(d),ts=state.tasks.filter(t=>t.date===key),total=ts.reduce((n,t)=>n+Number(t.duration),0),done=ts.filter(t=>t.done).reduce((n,t)=>n+Number(t.duration),0);return `<div class="bar-day"><div class="bar-wrap"><div class="bar ${key===dayKey(today)?'today':''}" style="height:${Math.max(7,total/180*78)}px;--done:${total?done/total*100:0}%" title="${fmtHours(total)} planned, ${fmtHours(done)} completed"></div></div><span class="${key===dayKey(today)?'today-label':''}">${fmt(d,{weekday:'short'}).slice(0,2)}</span></div>`}).join('')}
  function renderSubjects(){const el=document.getElementById('subjects');el.innerHTML=state.subjects.length?state.subjects.map(s=>{const ts=state.tasks.filter(t=>t.subject===s.id),mins=ts.reduce((n,t)=>n+Number(t.duration),0);return `<div class="subject-line"><i class="subject-dot-lg" style="background:${s.color}"></i><div><b>${esc(s.name)}</b><small>${ts.length} session${ts.length===1?'':'s'} planned</small></div><strong>${fmtHours(mins)}</strong><button class="subject-remove" type="button" data-remove-subject="${esc(s.id)}" aria-label="Remove ${esc(s.name)}" title="Remove subject">×</button></div>`}).join(''):`<div class="empty-state">Add your first subject to organize your study time.</div>`}  const prettySize=bytes=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(0)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
  function renderFiles(){const select=document.getElementById('file-subject'),selected=select.value;select.innerHTML=`<option value="">General resources</option>${state.subjects.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}`;if([...select.options].some(o=>o.value===selected))select.value=selected;getFiles().then(records=>{records.sort((a,b)=>b.addedAt-a.addedAt);const total=records.reduce((n,r)=>n+r.size,0);document.getElementById('file-summary').textContent=records.length?`${records.length} file${records.length===1?'':'s'} · ${prettySize(total)} saved in this browser`:'Upload notes, worksheets, syllabi, and other study files';document.getElementById('file-list').innerHTML=records.length?records.map(r=>{const ext=(r.name.split('.').pop()||'FILE').slice(0,5).toUpperCase(),s=subject(r.subjectId),canPreview=r.type==='application/pdf'||['image/png','image/jpeg','image/gif','image/webp'].includes(r.type);return `<div class="file-row"><span class="file-icon">${esc(ext)}</span><div class="file-info"><b title="${esc(r.name)}">${esc(r.name)}</b><small>${esc(s.name==='Independent study'?'General resources':s.name)} · ${prettySize(r.size)}</small></div><div class="file-actions">${canPreview?`<button class="file-action" data-file-open="${esc(r.id)}">Open</button>`:''}<button class="file-action" data-file-download="${esc(r.id)}">Download</button><button class="file-action delete" data-file-delete="${esc(r.id)}" aria-label="Remove ${esc(r.name)}">Remove</button></div></div>`}).join(''):`<div class="empty-state">No files yet. Upload your first study material above.</div>`}).catch(()=>{document.getElementById('file-summary').textContent='File storage is unavailable in this browser';document.getElementById('file-list').innerHTML='<div class="empty-state">Allow browser storage for this site to save study materials.</div>'})}
  function iconSvg(name){const paths={clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<path d="m5 12 4 4L19 6"/>',chart:'<path d="M4 19V5m0 14h17M8 15v-4m5 4V7m5 8v-6"/>',calendar:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',spark:'<path d="m12 3 1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3ZM19 16l.7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`}
  let toastTimer;function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  const modal=document.getElementById('modal'),form=document.getElementById('form');function closeModal(){modal.classList.remove('show')}
  function openForm(kind){const cfg={task:{title:'Add a study task',submit:'Add task'},exam:{title:'Add an exam',submit:'Save exam'},subject:{title:'Add a subject',submit:'Add subject'}}[kind];document.getElementById('modal-title').textContent=cfg.title;
    if(kind==='task')form.innerHTML=`<div class="field"><label for="task-title">What do you need to study?</label><input id="task-title" required maxlength="80" placeholder="e.g. Review chapter 4"></div><div class="form-grid"><div class="field"><label for="task-subject">Subject</label><select id="task-subject" ${state.subjects.length?'':'disabled'}>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label for="task-priority">Priority</label><select id="task-priority"><option value="3">High</option><option value="2" selected>Medium</option><option value="1">Low</option></select></div></div><div class="form-grid"><div class="field"><label for="task-date">Study date</label><input id="task-date" type="date" value="${dayKey(today)}" min="${dayKey(today)}" required></div><div class="field"><label for="task-time">Start time</label><input id="task-time" type="time" value="09:00" required></div></div><div class="field"><label for="task-duration">Session length</label><select id="task-duration"><option value="25">25 minutes</option><option value="40">40 minutes</option><option value="50" selected>50 minutes</option><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120">2 hours</option></select></div>`;
    if(kind==='exam')form.innerHTML=`<div class="field"><label for="exam-subject">Exam or subject name</label><input id="exam-subject" required maxlength="60" placeholder="e.g. Chemistry midterm"></div><div class="field"><label for="exam-date">Exam date</label><input id="exam-date" type="date" value="${dayKey(addDays(today,7))}" min="${dayKey(today)}" required></div>`;
    if(kind==='subject')form.innerHTML=`<div class="field"><label for="subject-name">Subject name</label><input id="subject-name" required maxlength="40" placeholder="e.g. Physics"></div>`;
    form.innerHTML+=`<div class="modal-actions"><button type="button" class="cancel" id="cancel">Cancel</button><button class="primary" type="submit">${cfg.submit}</button></div>`;modal.classList.add('show');setTimeout(()=>form.querySelector('input:not([type=date]):not([type=time])')?.focus(),30);
    document.getElementById('cancel').onclick=closeModal;form.onsubmit=e=>{e.preventDefault();if(kind==='task'){if(!state.subjects.length){toast('Add a subject first to organize tasks.');return}state.tasks.push({id:crypto.randomUUID(),title:form.querySelector('#task-title').value.trim(),subject:form.querySelector('#task-subject').value,date:form.querySelector('#task-date').value,time:form.querySelector('#task-time').value,duration:Number(form.querySelector('#task-duration').value),priority:Number(form.querySelector('#task-priority').value),done:false});toast('Study task added to your plan.')}else if(kind==='exam'){state.exams.push({id:crypto.randomUUID(),subject:form.querySelector('#exam-subject').value.trim(),date:form.querySelector('#exam-date').value});toast('Exam date saved.')}else{const name=form.querySelector('#subject-name').value.trim();if(state.subjects.some(s=>s.name.toLowerCase()===name.toLowerCase())){toast('That subject is already on your list.');return}state.subjects.push({id:crypto.randomUUID(),name,color:palette[state.subjects.length%palette.length]});toast('Subject added.')}save();closeModal();render()};}
  function autoPlan(){const pending=state.tasks.filter(t=>!t.done&&t.date>=dayKey(today));if(!pending.length){toast('Add a task first, then I can place it in your week.');return}let count=0;pending.forEach((t,i)=>{if(t.date!==dayKey(today))return;let target=today;for(let d=0;d<6;d++){const day=addDays(today,d);const key=dayKey(day);const scheduled=state.tasks.filter(x=>x.date===key);const total=scheduled.reduce((n,x)=>n+Number(x.duration),0);if(total+Number(t.duration)<=180){target=day;break}}if(dayKey(target)!==t.date){t.date=dayKey(target);count++}});const future=state.tasks.filter(t=>!t.done&&t.date>=dayKey(today)).sort((a,b)=>a.date.localeCompare(b.date)||b.priority-a.priority);future.forEach(t=>{const same=state.tasks.filter(x=>x.date===t.date&&x.id!==t.id);const end=same.reduce((max,x)=>Math.max(max,Number(x.time.slice(0,2))*60+Number(x.time.slice(3))+Number(x.duration)),9*60);if(end+Number(t.duration)<=19*60)t.time=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`});save();render();toast(count?`Week planned. ${count} task${count===1?'':'s'} moved to a lighter day.`:'Your week is organized around your tasks.')}
  document.getElementById('add-task').onclick=()=>openForm('task');document.getElementById('add-exam').onclick=()=>openForm('exam');document.getElementById('add-subject').onclick=()=>openForm('subject');document.getElementById('plan-week').onclick=autoPlan;document.getElementById('modal-close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
  document.getElementById('subjects').addEventListener('click',e=>{const button=e.target.closest('[data-remove-subject]');if(!button)return;const id=button.dataset.removeSubject,s=state.subjects.find(item=>item.id===id);if(!s)return;const taskCount=state.tasks.filter(t=>t.subject===id).length;const detail=taskCount?` ${taskCount} task${taskCount===1?'':'s'} will stay in your planner as independent study.`:' Its planner data will be kept.';if(!confirm(`Remove "${s.name}"?${detail}`))return;state.subjects=state.subjects.filter(item=>item.id!==id);save();render();toast(`${s.name} removed.`)});
  const fileInput=document.getElementById('file-input'),fileDrop=document.getElementById('file-drop');
  async function addFiles(fileList){const files=[...fileList];if(!files.length)return;let saved=0,tooLarge=0;for(const file of files){if(file.size>MAX_FILE_SIZE){tooLarge++;continue}try{await putFile({id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type||'application/octet-stream',addedAt:Date.now(),subjectId:document.getElementById('file-subject').value||'',ownerId:currentUser.id,blob:file});saved++}catch{toast('Browser storage is full or unavailable. Try a smaller file.');break}}renderFiles();if(saved)toast(`${saved} file${saved===1?'':'s'} added to Study materials.`);if(tooLarge)toast(`${tooLarge} file${tooLarge===1?' was':'s were'} over the 20 MB limit.`)}
  document.getElementById('choose-files').onclick=()=>fileInput.click();fileInput.onchange=()=>{addFiles(fileInput.files);fileInput.value=''};
  for(const eventName of ['dragenter','dragover'])fileDrop.addEventListener(eventName,e=>{e.preventDefault();fileDrop.classList.add('dragover')});for(const eventName of ['dragleave','drop'])fileDrop.addEventListener(eventName,e=>{e.preventDefault();fileDrop.classList.remove('dragover')});fileDrop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));fileDrop.addEventListener('click',e=>{if(e.target.closest('#choose-files'))return;if(e.target===fileDrop||e.target.closest('.file-drop-copy'))fileInput.click()});
  document.getElementById('file-list').addEventListener('click',async e=>{const open=e.target.closest('[data-file-open]'),download=e.target.closest('[data-file-download]'),remove=e.target.closest('[data-file-delete]');if(open||download){const id=(open||download).dataset.fileOpen||(open||download).dataset.fileDownload,popup=open?window.open('about:blank','_blank'):null;if(popup)popup.opener=null;try{const record=await getFile(id);if(!record||record.ownerId!==currentUser.id){if(popup)popup.close();return}const url=URL.createObjectURL(record.blob);if(open&&popup){popup.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),120000)}else{if(popup)popup.close();const a=document.createElement('a');a.href=url;a.download=record.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);if(open)toast('Preview was blocked; file downloaded instead.')}}catch{if(popup)popup.close();toast('Could not open that file.')}}else if(remove){const id=remove.dataset.fileDelete;if(!confirm('Remove this file from Study materials?'))return;try{await deleteFile(id);renderFiles();toast('File removed.')}catch{toast('Could not remove that file.')}}});
  document.getElementById('schedule').addEventListener('click',e=>{const b=e.target.closest('[data-toggle]');if(!b)return;const t=state.tasks.find(t=>t.id===b.dataset.toggle);if(t){t.done=!t.done;save();render();toast(t.done?'Session complete. Nice work!':'Session marked as not complete.')}});
  document.getElementById('weekly-goal').onclick=()=>{const val=prompt('Set your weekly study goal in hours:',state.goal);if(val===null)return;const n=Number(val);if(Number.isFinite(n)&&n>0&&n<=100){state.goal=n;save();render()}else toast('Enter a number of hours from 1 to 100.')};
  document.getElementById('nav-plan').onclick=()=>document.querySelector('.content-grid').scrollIntoView({behavior:'smooth'});document.getElementById('nav-subjects').onclick=()=>document.querySelector('.below-grid').scrollIntoView({behavior:'smooth'});
  const authPage=document.getElementById('auth-page'),appShell=document.getElementById('app-shell');
  const authForm=document.getElementById('auth-form'),authError=document.getElementById('auth-error');
  const authUsername=document.getElementById('auth-username'),authPassword=document.getElementById('auth-password');
  const confirmField=document.getElementById('confirm-field'),authConfirm=document.getElementById('auth-confirm');
  let authMode='login';
  function setAuthMode(mode){authMode=mode;const signup=mode==='signup';document.getElementById('mode-login').classList.toggle('active',!signup);document.getElementById('mode-signup').classList.toggle('active',signup);document.getElementById('auth-title').textContent=signup?'Create your Studyflow account':'Sign in to Studyflow';document.getElementById('auth-description').textContent=signup?'Choose a username and password to create your private planner.':'Log in to open your personal study planner.';document.getElementById('auth-submit').textContent=signup?'Create account':'Sign in';confirmField.hidden=!signup;authConfirm.required=signup;authConfirm.value='';authPassword.autocomplete=signup?'new-password':'current-password';authError.textContent=''}
  async function startSession(user){const activeUser=user||(await api('/api/auth/me')).user;const result=await api('/api/planner');currentUser=activeUser;state=result.planner||{goal:12,subjects:[],tasks:[],exams:[]};state.goal=Number(state.goal)||12;state.subjects=Array.isArray(state.subjects)?state.subjects:[];state.tasks=Array.isArray(state.tasks)?state.tasks:[];state.exams=Array.isArray(state.exams)?state.exams:[];document.getElementById('account-name').textContent=`@${activeUser.username}`;authPage.hidden=true;appShell.hidden=false;authError.textContent='';render()}
  document.getElementById('mode-login').onclick=()=>setAuthMode('login');document.getElementById('mode-signup').onclick=()=>setAuthMode('signup');
  authForm.onsubmit=async event=>{event.preventDefault();authError.textContent='';const button=document.getElementById('auth-submit');button.disabled=true;button.textContent=authMode==='signup'?'Creating account…':'Signing in…';try{if(authMode==='signup'&&authPassword.value!==authConfirm.value)throw new Error('The passwords do not match.');const result=await api(authMode==='signup'?'/api/auth/signup':'/api/auth/login',{method:'POST',body:JSON.stringify({username:authUsername.value,password:authPassword.value})});authPassword.value='';authConfirm.value='';await startSession(result.user)}catch(error){authError.textContent=error.message||'Could not sign in. Please try again.'}finally{button.disabled=false;button.textContent=authMode==='signup'?'Create account':'Sign in'}};
  document.getElementById('logout').onclick=async()=>{try{await flushSave()}catch{toast('Your latest changes may not have saved.')}try{await api('/api/auth/logout',{method:'POST'})}catch{}currentUser=null;state={goal:12,subjects:[],tasks:[],exams:[]};appShell.hidden=true;authPage.hidden=false;authUsername.value='';authPassword.value='';setAuthMode('login');authUsername.focus()};
  (async()=>{try{await startSession()}catch(error){authPage.hidden=false;appShell.hidden=true;if(error.status!==401)authError.textContent='Could not connect to Studyflow. Refresh the page and try again.'}})();
})();